apiVersion: 1
datasources:
  - name: GrideX Market RO
    uid: gridex-market-ro
    type: postgres
    access: proxy
    url: gridex-market-db:5432
    user: gridex_grafana_market_ro
    isDefault: false
    editable: false
    jsonData:
      database: gridex_market
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
      maxOpenConns: 5
    secureJsonData:
      password: $__env{GRIDEX_GRAFANA_MARKET_READER_PASSWORD}
