import test from 'node:test';
import assert from 'node:assert/strict';
import {parseSystemTelemetry,parseTemperature,validateHistoryBindings} from './history-ingest.mjs';
const ids={siteId:'11111111-1111-4111-8111-111111111111',gatewayId:'22222222-2222-4222-8222-222222222222',assetId:'AbCdEfGhIjKlMnOpQrStUv'};
const at=new Date().toISOString(), topic='gridex/v1/sites/lab/edge/rock/system/telemetry';
test('accepts allowlisted ROCK system metrics and rejects invalid values',()=>{const b=['cpuTemperatureC','load1','memoryAvailableBytes'].map(metric=>({...ids,metric,sourceGateway:'rock-pi-e',topic}));assert.equal(validateHistoryBindings(b).length,3);const out=parseSystemTelemetry(topic,Buffer.from(JSON.stringify({schemaVersion:1,gatewayId:'rock-pi-e',observedAt:at,samples:[{sensorId:'cpuTemperatureC',value:48.2},{sensorId:'load1',value:.37},{sensorId:'memoryAvailableBytes',value:0},{sensorId:'cpuTemperatureC',value:999}]})),b);assert.deepEqual(out.map(x=>x.metric),['cpuTemperatureC','load1','memoryAvailableBytes']);});
test('keeps legacy health temperature contract',()=>{const b={...ids,metric:'cpuTemperatureC',sourceGateway:'rock-pi-e',topic:topic.replace('/system/telemetry','/health')};assert.equal(parseTemperature(b.topic,Buffer.from(JSON.stringify({schemaVersion:1,gatewayId:'rock-pi-e',observedAt:at,cpuTemperatureC:51.1})),b).value,51.1);});
test('rejects unapproved topic or metric',()=>{assert.throws(()=>validateHistoryBindings([{...ids,metric:'shellOutput',sourceGateway:'rock',topic}]));assert.throws(()=>validateHistoryBindings([{...ids,metric:'load1',sourceGateway:'rock',topic:topic.replace('system/telemetry','+#')}]));});
test('rejects foreign gateway, bad sample time and wrong unit',()=>{const b={...ids,metric:'load1',sourceGateway:'rock-pi-e',topic};const payload={schemaVersion:1,gatewayId:'other-rock',observedAt:at,samples:[{sensorId:'load1',value:.4,unit:'load',observedAt:'not-a-date'},{sensorId:'load1',value:.4,unit:'Cel'}]};assert.deepEqual(parseSystemTelemetry(topic,Buffer.from(JSON.stringify(payload)),[b]),[]);});
